[package]
name = "zkvm-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
block_header = { workspace = true, features = ["test-utils"] }
block_trie = { workspace = true }
call_precompiles = { workspace = true }
common = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }

email_proof = { workspace = true }
mpt = { workspace = true }
risc0-zkvm = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

frost-core = {version = "^2.0.0"}
frost-ed25519 = {version = "^2.0.0"}
frost-ristretto255 = {version = "^2.0.0"}
frost-ed448 = {version = "^2.0.0"}
frost-p256 = {version = "^2.0.0"}
frost-secp256k1 = {version = "^2.0.0"}
rand = "0.8.5"

[lints]
workspace = true
