[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = { workspace = true }
jwt-simple = { workspace = true }
serde = { workspace = true }
strum = { workspace = true, features = ["derive"] }

[lints]
workspace = true
