name: Create reusable Cargo target dir
description: Creates a reusable Cargo target directory in a custom subdirectory.
inputs:
  target_name:
    description: 'Unique name for separating the target from others.'
    required: true
outputs:
  CARGO_TARGET_DIR:
    description: "The variable to use to override the target dir."
    value: ${{ steps.configure_cargo_target.outputs.CARGO_TARGET_DIR }}
runs:
  using: "composite"
  steps:
    - name: Configure the CARGO_TARGET_DIR variable
      id: configure_cargo_target
      run: |
        mkdir -p "${{ vars.VLAYER_CARGO_TARGET_DIRS }}/${{ inputs.target_name }}"
        echo "CARGO_TARGET_DIR=${{ vars.VLAYER_CARGO_TARGET_DIRS }}/${{ inputs.target_name }}" >> $GITHUB_OUTPUT
      shell: bash
