name: Reuse Cargo target dir
description: Reuses the Cargo target directory, separately for each compilation step.
inputs:
  target_name:
    description: 'Unique name for separating the target from others.'
    required: true
outputs:
  CARGO_TARGET_DIR:
    description: "The variable to use to override the target dir."
    value: ${{ steps.configure_cargo_target.outputs.CARGO_TARGET_DIR }}
runs:
  using: "composite"
  steps:
    - name: Configure the CARGO_TARGET_DIR variable
      id: configure_cargo_target
      run: |
        echo "CARGO_TARGET_DIR=/tmp/vlayer_targets/${{ inputs.target_name }}" >> $GITHUB_OUTPUT
      shell: bash
