[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
derive_more = { workspace = true }
risc0-zkp = { workspace = true }
serde = { workspace = true }

[features]
testing = []

[lints]
workspace = true
