[package]
name = "call_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
serde_json = { workspace = true }
web_proof = { workspace = true }

[lints]
workspace = true

