[package]
name = "tlsn_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.3", default-features = false, features = ["std"] }
web_proof = { path = "../../.." }

[patch.crates-io]
ring = { git = "https://github.com/briansmith/ring.git", rev = "7c0024abaf4fd59250c9b79cc41a029aa0ef3497" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
