[[bin]]
name = "vld"
path = "src/main.rs"

[package]
name = "vld"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive", "env", "string"] }

[lints]
workspace = true
