[package]
name = "call_host"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
anyhow = { workspace = true }
bytes = { workspace = true }
host_utils = { workspace = true }
lazy_static = { workspace = true }
risc0-zkvm = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }

[dev-dependencies]
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
dotenvy = { workspace = true }
ethers-providers = { workspace = true }
guest_wrapper = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
maplit = { workspace = true }
test-log = { workspace = true }

[lints]
workspace = true
