[package]
name = "call_host"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
block_header = { workspace = true }
bytes = { workspace = true }
call_common = { workspace = true }
call_engine = { workspace = true }
chain = { workspace = true }
common = { workspace = true }
derive-new = { workspace = true }
derive_more = { workspace = true }
host_utils = { workspace = true }
mpt = { workspace = true }
provider = { workspace = true }
revm = { workspace = true, features = ["serde", "std"] }
risc0-zkvm = { workspace = true }
seal = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
dotenvy = { workspace = true }
ethers-providers = { workspace = true }
guest_wrapper = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
maplit = { workspace = true }
test-log = { workspace = true }

[lints]
workspace = true
