[package]
name = "tlsn_test_host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tlsn_test_methods = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
web_proof = { workspace = true }
