[package]
name = "zkvm-benchmarks-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
common = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
host_utils = { workspace = true }
insta = { workspace = true }
risc0-zkvm = { workspace = true }
tabled = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
zkvm-benchmarks = { workspace = true }

frost-ed25519 = {version = "^2.0.0"}
rand = "0.8.5"

[build-dependencies]
anyhow = { workspace = true }
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["risc0_guest"]

[lints]
workspace = true
