name: Alert on failed release
on:
  workflow_run:
    workflows:
      - "Release vlayer artifacts"
      - "Deploy Provers"
      - "Deploy Chain Services"
      - "Test Release"
    types: [completed]
  push:
jobs:
  alert-failed-release:
    # if: ${{ github.repository == 'vlayer-xyz/vlayer' && github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification to team-devops channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_TEAM_DEVOPS }}
        run: |
          MESSAGE="Just a test. <https://www.google.com>"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               "$DISCORD_WEBHOOK"
