name: Lint Rust

on:
  pull_request:
    paths:
      - "rust-toolchain.toml"
      - "rust/**"
      - ".github/workflows/lint_rust.yaml"
  merge_group:
  push:
    # branches:
    #   - main
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-rust:
    strategy:
      fail-fast: false
      matrix:
        a: [1,2,3,4]
    name: Lint Rust
    runs-on: aws-linux-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2
      - name: Install Rust prerequisites
        id: rust_pre
        uses: ./.github/actions/rust-prerequisites
      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites
      - run: mkdir -p /tmp/vlayer_targets/{lint-rust-host,lint-rust-call-guest,lint-rust-chain-guest}

      - name: Run Host lints
        env:
          CARGO_TARGET_DIR: /tmp/vlayer_targets/lint-rust-host
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo +nightly fmt --check
          cargo sort --check --grouped --workspace
          cargo clippy --all-targets --all-features --locked

      - name: Run Risc0 Call Guest lints
        working-directory: rust/guest_wrapper/risc0_call_guest
        env:
          CARGO_TARGET_DIR: /tmp/vlayer_targets/lint-rust-call-guest
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo +nightly fmt --check
          cargo sort --check --grouped
          cargo clippy --all-targets --all-features --locked

      - name: Run Risc0 Chain Guest lints
        working-directory: rust/guest_wrapper/risc0_chain_guest
        env:
          CARGO_TARGET_DIR: /tmp/vlayer_targets/lint-rust-chain-guest
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo +nightly fmt --check
          cargo sort --check --grouped
          cargo clippy --all-targets --all-features --locked

      - name: Run cargo deny
        working-directory: rust/cli
        env:
          CARGO_TARGET_DIR: /tmp/vlayer_targets/${{ github.workflow }}
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
        run: cargo deny check bans

      - name: Detect unused dependencies
        env:
          CARGO_TARGET_DIR: /tmp/vlayer_targets/${{ github.workflow }}
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
        run: cargo machete

      - name: Check chain guest ELF ID
        run: ./bash/check-elf-id.sh
