name: E2E test with Bonsai and OP Sepolia

# This workflow has additional constraints to run on `main`,
# because it uses external API resources.

on:
  push:
    branches:
      - main
    # If any path names do not match patterns in paths-ignore,
    # even if some path names match the patterns,
    # the workflow will run.
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "book/**"
  pull_request:
  merge_group:
  workflow_dispatch:
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code-changes: ${{ steps.filter.outputs.code-changes }}
      workflow-changes: ${{ steps.filter.outputs.workflow-changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # We detect code changes, and run the workflow only if relevant code or workflow changes are detected.
      # Because the workflow is resource heavy (in time/compilation, in testnet ETH usage, and in Bonsai API usage),
      # we also skip running the workflow on every commit of PRs (unless the workflow configuration is changed)
      # Red PR cannot be merged because even though PR commits are skipped, the workflow will still run in the merge queue.
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code-changes:
              - 'rust/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'bash/**'
              - 'contracts/**'
              - 'examples/**'
              - 'packages/**'
              - 'docker/**'
              - 'ansible/**'
              - 'bun.lock'
            workflow-changes:
              - '.github/workflows/**'
              - '.github/actions/test-e2e/**'

  build-binaries:
    name: Build binaries
    needs: changes
    runs-on: aws-linux-medium
    if: github.event_name == 'push' || github.event_name == 'pull_request' || needs.changes.outputs.workflow-changes == 'true' || (github.event_name != 'pull_request' && needs.changes.outputs.code-changes == 'true')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust prerequisites
        id: rust_pre
        uses: ./.github/actions/rust-prerequisites

      - name: Install Risc0 prerequisites
        uses: ./.github/actions/risc0

      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites

      - name: Check clang and LLVM version
        env:
          EXPECTED_LLVM_VERSION: "18.1"
        run: bash/check-llvm-clang.sh

      - name: Install contracts' dependencies
        working-directory: ./contracts/vlayer
        run: forge soldeer install

      - name: Create reusable Cargo target dir
        id: cargo_target
        uses: ./.github/actions/reuse-cargo-target
        with:
          targets_path: ${{ vars.VLAYER_CARGO_TARGET_DIRS }}
          target_name: test-e2e-bonsai-opsepolia
      - name: Build binaries
        env:
          CARGO_TARGET_DIR: ${{ steps.cargo_target.outputs.CARGO_TARGET_DIR }}
          RISC0_USE_DOCKER: 1
          RUSTC_WRAPPER: ${{ steps.rust_pre.outputs.RUSTC_WRAPPER }}
        run: |
          cargo build --bin vlayer --bin call_server --bin chain_server --bin worker --bin dns_server
          mkdir target_debug
          mv ${CARGO_TARGET_DIR}/debug/{vlayer,call_server,chain_server,worker,dns_server} target_debug/

      - name: Push binaries
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: target-debug
          path: target_debug
          if-no-files-found: error
          retention-days: 3

  test-e2e-bonsai-opsepolia-simple-teleport:
    name: E2E test (simple-teleport) with Bonsai and OP Sepolia
    needs: [changes, build-binaries]
    runs-on: aws-linux-medium

    env:
      GAS_PRICE_THRESHOLD: 63
      SEPOLIA_RPC_URL: https://eth-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}

    # Sepolia gas price chart reference: https://owlracle.info/sepolia
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip if gas price is too high
        id: gas_price_limiter
        run: |
          chmod +x ./bash/check-gas-price.sh
          if ./bash/check-gas-price.sh "${SEPOLIA_RPC_URL}" "${GAS_PRICE_THRESHOLD}"; then
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Run E2E Test (simple-teleport)
        if: steps.gas_price_limiter.outputs.skip == 'false'
        uses: ./.github/actions/test-e2e
        with:
          example: "simple-teleport"

          # JWT auth related
          jwt_auth: "on"
          vlayer_api_token: ${{ secrets.VLAYER_API_TOKEN_MAINNET }}

          # Proving related
          proving_mode: "prod"
          bonsai_api_url: ${{ vars.BONSAI_API_URL }}
          bonsai_api_key: ${{ secrets.BONSAI_API_KEY }}

          # Chain related
          chain_name: "sepolia"
          testnet_private_key_location: ${{ secrets.TESTNET_PRIVATE_KEY_LOCATION }}
          quicknode_api_key: ${{ secrets.QUICKNODE_API_KEY }}
