name: Test Release
on:
  push:
  workflow_run:
    workflows: ["Deploy Stable Provers"]
    types: [completed]
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test_release.yaml"
      - "docker/docker-compose.devnet.yaml"
      - "bash/test-release-local-prover.sh"
      - "bash/test-release-remote-prover.sh"
      - "bash/test-js-sdk-release.sh"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  test-release-anvil:
    name: Test release on anvil and local prover
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          submodules: recursive
      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites
      - name: Test local prover
        run: bash/test-release-local-prover.sh
        env:
          EXAMPLE: "simple-web-proof"
