name: Web Proof Vercel

on:
  push:
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  web-proof-vercel:
    name: Web Proof Vercel
    runs-on: aws-linux-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust prerequisites
        id: rust_pre
        uses: ./.github/actions/rust-prerequisites
      - name: Install Risc0 prerequisites
        uses: ./.github/actions/risc0
      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites
      - name: Check clang and LLVM version
        env:
          EXPECTED_LLVM_VERSION: "18.1"
        run: bash/check-llvm-clang.sh

      - name: Check nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          flake-lock-path: ./.github/nix/flake.lock
          check-outdated: false
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build binaries
        run: |
          nix develop .github/nix/. --command bash -c "cd rust/web_proof_vercel && cargo build --release"
        env:
          RUST_LOG: info

      - name: Push artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: web_proof_vercel
          path: rust/web_proof_vercel/target
          if-no-files-found: error
          retention-days: 3
