name: Web Proof Vercel

on:
  push:
concurrency:
  # Do not cancel jobs on main by forcing a unique group name.
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  web-proof-vercel:
    name: Web Proof Vercel
    runs-on: aws-linux-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust prerequisites
        id: rust_pre
        uses: ./.github/actions/rust-prerequisites
      - name: Install Risc0 prerequisites
        uses: ./.github/actions/risc0
      - name: Install contracts prerequisites
        uses: ./.github/actions/contracts-prerequisites
      - name: Check clang and LLVM version
        env:
          EXPECTED_LLVM_VERSION: "18.1"
        run: bash/check-llvm-clang.sh

      - name: Check nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          flake-lock-path: ./.github/nix/flake.lock
          check-outdated: false
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build binaries
        run: |
          nix develop .github/nix/. --command bash -c "cd rust/web_proof_vercel && cargo build --release"
        env:
          RUST_LOG: info

      - name: Push artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: web_proof_vercel
          path: rust/web_proof_vercel/target
          if-no-files-found: error
          retention-days: 3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (preview)
        if: github.event_name == 'pull_request'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: prj_5tiX2JHrZPwd2sHgIzH05aLOI2PB
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rust/web_proof_vercel
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --yes --scope $VERCEL_ORG_ID | tail -1)
          COMMENT_BODY="The preview of the web-proof-vercel API is available at: $DEPLOYMENT_URL"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\":\"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
